### ISSUE TITLE
Support minSdkVersion="8"

### ISSUE THREAD

**Issue by heypaulmcgrath** [mattprecious/telescope#19]
Hey Matt, 

I was just wondering if you intend backporting this library to minSdkVersion 8, or if you wouldn't mind accepting pull requests for these changes.

Thanks!

**Comment by mattprecious** [comment]
I wasn't planning on doing any backporting. SDK 8-14 are sitting at ~6.8% of market share and dropping. It's not a lot of work to update the current code, but I worry about being tied to SDK 8 for future updates.

This library is small enough that I don't think it's unreasonable for you to copy it into your app to make the changes you need.

**Comment by heypaulmcgrath** [comment]
Great, I'll do that so. Thanks for replying, and for the great talk at Droidcon Montreal.

**Comment by athkalia** [comment]
Just wondering, what's the min sdk supported at the moment ?

**Comment by mattprecious** [comment]
[14](https://github.com/mattprecious/telescope/blob/master/telescope/src/main/AndroidManifest.xml#L7)

**Comment by athkalia** [comment]
I never even thought of looking at that, sorry for wasting your time!
