### ISSUE TITLE
Google Maps in a screenshot

### ISSUE THREAD

**Issue by tasomaniac** [mattprecious/telescope#21]
When I have Google Maps in the hierarchy the screenshot shows just a black surface. Here is the screenshot taken with Telescope. 

![telescope-2015-09-08-100034](https://cloud.githubusercontent.com/assets/763339/9731424/7bd43040-5625-11e5-8940-756c0ef0d4d8.png)

I think #13 would fix this for > Lollipop devices.

**Comment by mattprecious** [comment]
I believe this is a similar issue to #18. Another team internally has worked around this by manually invalidating the drawing cache when telescope is triggered. I'll try to dig up the code and put together a sample.

**Comment by athkalia** [comment]
That would be lovely, I am facing the same issue

**Comment by hzsweers** [comment]
This can be closed with version 2.0 right?

**Comment by stkent** [comment]
The 2.0 release notes suggest that this will no longer be a problem on 21+, not sure about 20 and below.

**Comment by mattprecious** [comment]
Yeah, this shouldn't be an issue anymore on 21+ unless the user denies the permission to record the screen. I'd still like to solve this for pre-21, though... @tasomaniac, you made the change to `Lens` to be able to solve this, right? Can you post a sample somewhere?

**Comment by tasomaniac** [comment]
Sorry all I have it for devices below 21 in my codebase. It's in my to do
list to open a pr here. I couldn't find time yet. I will do it soon.

I don't want to include play Services to your sample. Should I do that? Or
should I add another sample module with GMS just for maps?

**Comment by mattprecious** [comment]
Unless it's going to crash on emulators without play services then I don't mind adding it to the sample.
