### ISSUE TITLE
Make it easier to use telescope

### ISSUE THREAD

**Issue by reisub** [mattprecious/telescope#25]
Is there a possibility of using telescope (or modifying it to be used) without having to add the TelescopeLayout to each of the activity layouts?

I'm thinking of something like adding a bit of code to the BaseActivity and then being able to enable bug reporting for every screen in the app for alpha/beta builds.

**Comment by mattprecious** [comment]
If you have a base activity, you can wrap your content with a `TelescopeLayout` there instead of in the layout files.

```java
@Override protected void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);

  TelescopeLayout telescopeLayout = new TelescopeLayout(this);
  // TODO: Set up Telescope...
  getLayoutInflater().inflate(R.layout.your_layout, telescopeLayout, true);
  setContentView(telescopeLayout);
}
```

Does that work for you?

**Comment by reisub** [comment]
@mattprecious that will do just fine, thanks!
