### ISSUE TITLE
Undefined behavior when another app is using the screen record API

### ISSUE THREAD

**Issue by ZacSweers** [mattprecious/telescope#39]
Was trying to put together a little demo video using this (v2) and didn't think about what would happen. Specifically, I was using [AndroidTool](https://github.com/mortenjust/androidtool-mac) to record a video. When I started the screen grab via telescope though, it appears to start, but then never completes/calls back to the lens.

**Comment by mattprecious** [comment]
Hmm... I didn't consider this. Ideally something throws an exception somewhere and we get notified and fall back to the canvas screenshot, but it sounds like that might not be happening. I'll take a look!

**Comment by hzsweers** [comment]
Cool, thanks for looking into it. Let me know if there's anything I can do to help as far as testing fixes.
