### ISSUE TITLE
Stop using file:// uri for sharing screenshot

### ISSUE THREAD

**Issue by gabrielittner** [mattprecious/telescope#43]
When you target N sharing a `file://` uri will cause a `FileUriExposedException` [(source)](https://developer.android.com/preview/behavior-changes.html#permfilesys). There is also a StrictMode check for this since API 18.

**Comment by mattprecious** [comment]
Been meaning to look into this. I think I can use a [FileProvider](http://developer.android.com/reference/android/support/v4/content/FileProvider.html)...
