### ISSUE TITLE
Access to `MediaProjection` APIs cause `SecurityException` crash on Android 10

### ISSUE THREAD

**Issue by julioz** [mattprecious/telescope#75]
Crash being reported only on Android 10. The stack trace is as follows:

```
Caused by java.lang.SecurityException

Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
android.os.Parcel.createException (Parcel.java:2071)
android.os.Parcel.readException (Parcel.java:2039)
android.os.Parcel.readException (Parcel.java:1987)
android.media.projection.IMediaProjection$Stub$Proxy.start (IMediaProjection.java:231)
android.media.projection.MediaProjection.<init> (MediaProjection.java:58)
android.media.projection.MediaProjectionManager.getMediaProjection (MediaProjectionManager.java:104)
com.mattprecious.telescope.TelescopeLayout$4.onReceive (TelescopeLayout.java:198)
android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args (LoadedApk.java:1550)
android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run (-.java:2)
android.os.Handler.handleCallback (Handler.java:883)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7356)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:930)
```

**Comment by mattprecious** [comment]
Oh jeez... I really don't want to add a service.

**Comment by mattprecious** [comment]
I'm able to use this fine on my Pixel 2 running Android 10, so I'm not sure where this trace is coming from.

**Comment by julioz** [comment]
@mattprecious thanks for the prompt response. 

We got that from a user via crashlytics. I can dig up the report once again tomorrow and provide a bit more information.

Out of curiosity, I also couldn't reproduce on my Pixel 2 with Android 10 either.

**Comment by dturner** [comment]
To fix this you will need to add a foreground service. The foreground service requirement was introduced so that users will always be aware when their audio and/or video is being captured. 

Possibly helpful resources:
https://developer.android.com/guide/components/services

https://stackoverflow.com/questions/57026489/mediaprojection-service-type-not-recognized-in-android-q

**Comment by mattprecious** [comment]
Ah, I'm not targeting API 29 yet, so that's likely why I'm not seeing this. Should probably disable native capturing on 29 until it can be moved to service.
